# Generated by Django 4.2.6 on 2023-12-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('-created_at',)},
        ),
    ]
