# Generated by Django 4.2.6 on 2023-12-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
