# Generated by Django 4.2.6 on 2024-01-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcomment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('created_at',)},
        ),
    ]
