# Generated by Django 4.2.6 on 2024-02-19 04:54

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_blogcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, default='Testing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(blog.models.get_default_user), related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='Blog',
            field=models.ForeignKey(on_delete=models.SET(blog.models.get_default_blog), related_name='Comments', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(blog.models.get_default_user), related_name='Created_Comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
